import "./globals.css";
import ReactQueryProvider from "@components/useClient/ReactQueryProvider";
import Navbar from "@components/Navbar";
import Footer from "@components/Footer";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "VwFlex",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // Create a client

  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <section className="w-full  text-white  bg-slate-700 flex justify-center font-semibold text-xl sticky top-0 z-50">
            <Navbar />
          </section>
          <section className="w-full h-full">{children}</section>
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
